export const SITE = {
  name: "Velora",
  tagline: "AI-first browser runtime for automation, agents, and programmable web execution.",
  description:
    "Lightweight headless browser engine built for AI workflows, automation, and crawling — CDP-native, MCP-ready, and embeddable without the Chromium monolith.",
  githubUrl: "https://github.com/ivanUri/velora",
  docsUrl: "/docs",
  blogUrl: "/blog",
  featuresUrl: "/features",
  howItWorksUrl: "/how-it-works",
  benchmarksUrl: "/benchmarks",
  sdkUrl: "/sdk",
  license: "AGPL-3.0",
  locale: "en_US",
  twitterHandle: "@ivanUri",
  keywords: [
    "Velora",
    "headless browser",
    "browser automation",
    "CDP",
    "Chrome DevTools Protocol",
    "MCP",
    "AI agents",
    "web crawling",
    "Zig",
    "TypeScript SDK",
    "browser runtime",
    "playwright alternative",
    "automation infrastructure",
  ],
} as const;